---
title: "Joining Vectors"
author: "James Waterford"
date: "2023-03-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library()
```

## What are vectors?

Vectors are described as a *1-dimensional* matrix.

Vectors must remain as single data types:

- Numerical

- Character

- Logical

```{r vector}
c("Luna", "Avi", "Anita", "James", "Charles", "Damian", "Davinder") -> our_names
```

Lists can be entirely numerical.
```{r num_vector}
numlist <- 1:7
numlist %>% head()

seqlist <- seq(-50, 10, by = 5)
seqlist %>% str()
```

## Creating data frames from vectors

The most general way to do this is with the fucntion `data.frame()` :

```{r data_frame}
data.frame(our_names,numlist)
```

```{r data_frame}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)

table <- data.frame(length,width,height)
table$genus <- "Taxus"
table$species <- "baccata"

table %>% 
  min(.,lengt)


```
